"""Knowledge / meetings / infra entity field specs for generic DB skill CRUD.

Describes create/update/delete surface for training library, agent programs,
meeting rooms, git repos, machine nodes, and workspace settings. Consumed by
the db_fields registry alongside workspace and other domain packs.

Security: never expose encrypted secrets (encrypted_token, keys, etc.) as writable.
"""
from __future__ import annotations

from typing import Any

ENTITY_SPECS: dict[str, dict[str, Any]] = {
    "knowledge_folder": {
        "model": "KnowledgeFolder",
        "table": "knowledge_folders",
        "label": "Knowledge folder",
        "category": "ops",
        "owner_col": "user_id",
        "owner_via": None,
        "id_arg": "folder_id",
        "create_required": ["name"],
        "writable": ["parent_id", "name", "description"],
        "clearable": ["parent_id", "description"],
        "field_types": {
            "parent_id": "int",
        },
        "aliases": {
            "create": ["create_knowledge_folder", "add_knowledge_folder"],
            "update": ["update_knowledge_folder", "change_knowledge_folder"],
            "delete": ["delete_knowledge_folder"],
        },
    },
    "knowledge_file": {
        "model": "KnowledgeFile",
        "table": "knowledge_files",
        "label": "Knowledge file",
        "category": "ops",
        "owner_col": "user_id",
        "owner_via": None,
        "id_arg": "file_id",
        "create_required": ["name"],
        # content_text OK for notes; do not allow writing encrypted secrets.
        "writable": [
            "folder_id",
            "name",
            "description",
            "tags",
            "kind",
            "storage",
            "storage_path",
            "connection_id",
            "mime_type",
            "size_bytes",
            "content_text",
            "status",
        ],
        "clearable": [
            "folder_id",
            "description",
            "tags",
            "storage_path",
            "connection_id",
            "content_text",
        ],
        "field_types": {
            "folder_id": "int",
            "connection_id": "int",
            "size_bytes": "int",
        },
        "aliases": {
            "create": ["create_knowledge_file", "add_knowledge_file"],
            "update": ["update_knowledge_file", "change_knowledge_file"],
            "delete": ["delete_knowledge_file"],
        },
    },
    "agent_program": {
        "model": "AgentProgram",
        "table": "agent_programs",
        "label": "Agent program",
        "category": "ops",
        # Ownership via parent Agent.user_id (not a column on AgentProgram).
        "owner_col": None,
        "owner_via": {
            "parent": "Agent",
            "fk": "agent_id",
            "parent_owner": "user_id",
        },
        "id_arg": "program_id",
        "create_required": ["agent_id"],
        "writable": ["agent_id", "instructions", "policy_json"],
        "clearable": ["instructions", "policy_json"],
        "field_types": {
            "agent_id": "int",
        },
        "aliases": {
            "create": ["create_agent_program", "set_agent_program"],
            "update": ["update_agent_program", "change_agent_program"],
            "delete": ["delete_agent_program"],
        },
    },
    "meeting_room": {
        "model": "MeetingRoom",
        "table": "meeting_rooms",
        "label": "Meeting room",
        "category": "ops",
        "owner_col": "user_id",
        "owner_via": None,
        "id_arg": "meeting_id",
        "create_required": ["title"],
        "writable": [
            "company_id",
            "project_id",
            "task_id",
            "title",
            "purpose",
            "room_type",
            "status",
            "chair_agent_id",
            "settings_json",
            "summary_text",
        ],
        "clearable": [
            "company_id",
            "project_id",
            "task_id",
            "purpose",
            "chair_agent_id",
            "settings_json",
            "summary_text",
        ],
        "field_types": {
            "company_id": "int",
            "project_id": "int",
            "task_id": "int",
            "chair_agent_id": "int",
        },
        "aliases": {
            "create": ["open_meeting", "create_meeting", "create_meeting_room"],
            "update": ["update_meeting", "update_meeting_room", "change_meeting"],
            "delete": ["delete_meeting", "delete_meeting_room", "close_meeting"],
        },
    },
    "meeting_participant": {
        "model": "MeetingParticipant",
        "table": "meeting_participants",
        "label": "Meeting participant",
        "category": "ops",
        # Ownership via parent MeetingRoom.user_id.
        "owner_col": None,
        "owner_via": {
            "parent": "MeetingRoom",
            "fk": "room_id",
            "parent_owner": "user_id",
        },
        "id_arg": "participant_id",
        "create_required": ["room_id", "kind"],
        "writable": ["room_id", "kind", "user_id", "agent_id", "human_id", "role"],
        "clearable": ["user_id", "agent_id", "human_id"],
        "field_types": {
            "room_id": "int",
            "user_id": "int",
            "agent_id": "int",
            "human_id": "int",
        },
        "aliases": {
            "create": ["add_meeting_participant", "create_meeting_participant"],
            "update": ["update_meeting_participant", "change_meeting_participant"],
            "delete": ["remove_meeting_participant", "delete_meeting_participant"],
        },
    },
    "meeting_message": {
        "model": "MeetingMessage",
        "table": "meeting_messages",
        "label": "Meeting message",
        "category": "ops",
        # Ownership via parent MeetingRoom.user_id.
        "owner_col": None,
        "owner_via": {
            "parent": "MeetingRoom",
            "fk": "room_id",
            "parent_owner": "user_id",
        },
        "id_arg": "message_id",
        "create_required": ["room_id", "content"],
        "writable": [
            "room_id",
            "sender_kind",
            "content",
            "msg_type",
            "meta_json",
            "sender_agent_id",
            "sender_human_id",
            "sender_user_id",
        ],
        "clearable": [
            "meta_json",
            "sender_agent_id",
            "sender_human_id",
            "sender_user_id",
        ],
        "field_types": {
            "room_id": "int",
            "sender_agent_id": "int",
            "sender_human_id": "int",
            "sender_user_id": "int",
        },
        "aliases": {
            "create": ["post_to_meeting", "create_meeting_message", "add_meeting_message"],
            "update": ["update_meeting_message", "change_meeting_message"],
            "delete": ["delete_meeting_message"],
        },
    },
    "git_repo": {
        "model": "GitRepoConnection",
        "table": "git_repo_connections",
        "label": "Git repo",
        "category": "ops",
        "owner_col": "user_id",
        "owner_via": None,
        "id_arg": "repo_id",
        "create_required": ["name"],
        # NEVER include encrypted_token in writable.
        "writable": [
            "company_id",
            "agent_id",
            "provider",
            "name",
            "full_name",
            "clone_url",
            "html_url",
            "default_branch",
            "local_path",
            "machine_id",
            "token_hint",
            "scopes",
            "status",
            "last_error",
            "meta_json",
        ],
        "clearable": [
            "company_id",
            "agent_id",
            "full_name",
            "clone_url",
            "html_url",
            "local_path",
            "machine_id",
            "token_hint",
            "scopes",
            "last_error",
            "meta_json",
        ],
        "field_types": {
            "company_id": "int",
            "agent_id": "int",
            "machine_id": "int",
        },
        "aliases": {
            "create": ["connect_git_repo", "create_git_repo", "add_git_repo"],
            "update": ["update_git_repo", "change_git_repo"],
            "delete": ["disconnect_git_repo", "delete_git_repo"],
        },
    },
    "machine_node": {
        "model": "MachineNode",
        "table": "machine_nodes",
        "label": "Machine node",
        "category": "ops",
        "owner_col": "user_id",
        "owner_via": None,
        "id_arg": "machine_id",
        "create_required": ["name"],
        # public_id may be set/changed but is never clearable (unique identity).
        "writable": [
            "public_id",
            "name",
            "kind",
            "hostname",
            "os_name",
            "arch",
            "status",
            "agent_version",
            "snapshot_json",
            "labels",
        ],
        "clearable": [
            "hostname",
            "os_name",
            "arch",
            "agent_version",
            "snapshot_json",
            "labels",
        ],
        "field_types": {},
        "aliases": {
            "create": ["register_machine", "create_machine_node", "add_machine"],
            "update": ["update_machine_node", "change_machine"],
            "delete": ["delete_machine_node", "remove_machine"],
        },
    },
    "workspace_settings": {
        "model": "WorkspaceSettings",
        "table": "workspace_settings",
        "label": "Workspace settings",
        "category": "ops",
        "owner_col": "user_id",
        "owner_via": None,
        "id_arg": "settings_id",
        # Usually one row per user; create is upsert-style.
        "create_required": [],
        "upsert_by_owner": True,
        "writable": [
            "autonomy_enabled",
            "autonomy_interval_sec",
            "task_stuck_minutes",
            "last_autonomy_run",
            "last_autonomy_summary",
            "policy_json",
        ],
        "clearable": [
            "last_autonomy_run",
            "last_autonomy_summary",
            "policy_json",
        ],
        "field_types": {
            "autonomy_enabled": "bool",
            "autonomy_interval_sec": "int",
            "task_stuck_minutes": "int",
            "last_autonomy_run": "datetime",
        },
        "aliases": {
            "create": ["create_workspace_settings", "init_workspace_settings"],
            "update": ["update_workspace_settings", "configure_workspace"],
            "delete": ["delete_workspace_settings"],
        },
    },
}


def get_specs() -> dict[str, dict[str, Any]]:
    """Return the knowledge/meetings/infra entity field specs mapping."""
    return ENTITY_SPECS
