"""Workspace / ops entity field specs for generic DB skill CRUD.

Describes create/update/delete surface for core ops models (companies, projects,
tasks, humans, agents, memories, conversations, messages). Consumed by the
db_fields registry alongside CRM and other domain packs.
"""
from __future__ import annotations

from typing import Any

ENTITY_SPECS: dict[str, dict[str, Any]] = {
    "company": {
        "model": "Company",
        "table": "companies",
        "label": "Company",
        "category": "ops",
        "owner_col": "owner_user_id",
        "owner_via": None,
        "id_arg": "company_id",
        "create_required": ["name"],
        "writable": ["name", "industry", "notes"],
        "clearable": ["industry", "notes"],
        "field_types": {},
        "aliases": {
            "create": ["create_company", "add_company"],
            "update": ["update_company", "change_company"],
            "delete": ["delete_company"],
        },
    },
    "project": {
        "model": "Project",
        "table": "projects",
        "label": "Project",
        "category": "ops",
        "owner_col": "owner_user_id",
        "owner_via": None,
        "id_arg": "project_id",
        "create_required": ["name"],
        "writable": ["company_id", "name", "description", "status"],
        "clearable": ["company_id", "description"],
        "field_types": {
            "company_id": "int",
        },
        "aliases": {
            "create": ["create_project", "add_project"],
            "update": ["update_project", "change_project"],
            "delete": ["delete_project"],
        },
    },
    "task": {
        "model": "Task",
        "table": "tasks",
        "label": "Task",
        "category": "ops",
        "owner_col": "user_id",
        "owner_via": None,
        "id_arg": "task_id",
        "create_required": ["title"],
        "writable": [
            "project_id",
            "company_id",
            "agent_id",
            "human_id",
            "assignee_type",
            "parent_task_id",
            "meeting_id",
            "title",
            "description",
            "result",
            "status",
            "priority",
            "labels",
        ],
        # completed_at not primary writable; may be cleared / set via clearable path only.
        # tokens_used / cost are system-managed and excluded entirely.
        "clearable": [
            "project_id",
            "company_id",
            "agent_id",
            "human_id",
            "parent_task_id",
            "meeting_id",
            "description",
            "result",
            "labels",
            "completed_at",
        ],
        "field_types": {
            "project_id": "int",
            "company_id": "int",
            "agent_id": "int",
            "human_id": "int",
            "parent_task_id": "int",
            "meeting_id": "int",
            "completed_at": "datetime",
        },
        "aliases": {
            "create": ["create_task", "add_task"],
            "update": ["update_task", "change_task"],
            "delete": ["delete_task"],
        },
    },
    "human": {
        "model": "Human",
        "table": "humans",
        "label": "Human",
        "category": "ops",
        "owner_col": "owner_user_id",
        "owner_via": None,
        "id_arg": "human_id",
        "create_required": ["name"],
        "writable": [
            "email",
            "phone",
            "name",
            "role_title",
            "skills",
            "company_id",
            "project_id",
            "status",
            "capacity",
            "permission_level",
            "escalate_when",
            "escalate_reason",
            "escalate_to",
            "notes",
            "is_my_human",
        ],
        "clearable": [
            "email",
            "phone",
            "role_title",
            "skills",
            "company_id",
            "project_id",
            "escalate_reason",
            "notes",
        ],
        "field_types": {
            "company_id": "int",
            "project_id": "int",
            "capacity": "int",
            "is_my_human": "bool",
        },
        "aliases": {
            "create": ["create_human", "add_human"],
            "update": ["update_human", "change_human"],
            "delete": ["delete_human"],
        },
    },
    "agent": {
        "model": "Agent",
        "table": "agents",
        "label": "Agent",
        "category": "ops",
        "owner_col": "user_id",
        "owner_via": None,
        "id_arg": "agent_id",
        "create_required": ["name"],
        "writable": [
            "company_id",
            "project_id",
            "parent_id",
            "hierarchy_role",
            "is_lead",
            "name",
            "template_type",
            "personality",
            "model",
            "status",
            "idle_mode",
            "permission_level",
            "escalate_when",
            "escalate_reason",
            "escalate_to",
            "escalate_human_id",
            "config",
        ],
        "clearable": [
            "company_id",
            "project_id",
            "parent_id",
            "escalate_human_id",
            "escalate_reason",
            "personality",
            "config",
        ],
        "field_types": {
            "company_id": "int",
            "project_id": "int",
            "parent_id": "int",
            "is_lead": "bool",
            "escalate_human_id": "int",
        },
        "aliases": {
            "create": ["spawn_agent", "create_agent", "add_agent"],
            "update": ["configure_agent", "change_agent", "update_agent"],
            "delete": ["delete_agent"],
        },
    },
    "agent_memory": {
        "model": "AgentMemory",
        "table": "agent_memories",
        "label": "Agent Memory",
        "category": "ops",
        "owner_col": "user_id",
        "owner_via": None,
        "id_arg": "memory_id",
        "create_required": ["title", "content"],
        "writable": ["agent_id", "kind", "title", "content", "tags"],
        "clearable": ["tags", "kind"],
        "field_types": {
            "agent_id": "int",
        },
        "aliases": {
            "create": ["save_memory", "create_memory", "add_memory"],
            "update": ["update_memory", "change_memory"],
            "delete": ["delete_memory"],
        },
    },
    "conversation": {
        "model": "Conversation",
        "table": "conversations",
        "label": "Conversation",
        "category": "ops",
        "owner_col": "user_id",
        "owner_via": None,
        "id_arg": "conversation_id",
        "create_required": ["title"],
        "writable": ["agent_id", "project_id", "title", "mode"],
        "clearable": ["agent_id", "project_id"],
        "field_types": {
            "agent_id": "int",
            "project_id": "int",
        },
        "aliases": {
            "create": ["create_conversation", "add_conversation"],
            "update": ["update_conversation", "change_conversation"],
            "delete": ["delete_conversation"],
        },
    },
    "message": {
        "model": "Message",
        "table": "messages",
        "label": "Message",
        "category": "ops",
        # Ownership is via parent Conversation.user_id (not a column on Message).
        "owner_col": None,
        "owner_via": {
            "parent": "Conversation",
            "fk": "conversation_id",
            "parent_owner": "user_id",
        },
        "id_arg": "message_id",
        "create_required": ["conversation_id", "role", "content"],
        "writable": ["conversation_id", "role", "content"],
        "clearable": [],
        "field_types": {
            "conversation_id": "int",
        },
        "aliases": {
            "create": ["create_message", "add_message"],
            "update": ["update_message", "change_message"],
            "delete": ["delete_message"],
        },
    },
}


def get_specs() -> dict[str, dict[str, Any]]:
    """Return the workspace/ops entity field specs mapping."""
    return ENTITY_SPECS
