"""Agent-safe CRM entity / field specs for field-level skills.

Pure data — model class names are strings to avoid circular imports.
Consumers resolve `model` via `getattr(models, spec["model"])`.
"""
from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Entity specs
# ---------------------------------------------------------------------------

ENTITY_SPECS: dict[str, dict[str, Any]] = {
    # ── Customer ──────────────────────────────────────────────────────────
    "customer": {
        "model": "Customer",
        "table": "customers",
        "label": "Customer",
        "category": "crm",
        "owner_col": "owner_user_id",
        "owner_via": None,
        "id_arg": "customer_id",
        "create_required": ["name"],
        "create_defaults": {
            "status": "active",
            "source": "agent",
        },
        "writable": [
            "name",
            "email",
            "phone",
            "job_title",
            "account_name",
            "website",
            "industry",
            "address",
            "city",
            "country",
            "status",
            "source",
            "tags",
            "owner_human_id",
            "owner_agent_id",
            "annual_value",
            "notes",
            "external_source",
            "external_id",
            "meta_json",
            "company_id",
            "last_contacted_at",
        ],
        "clearable": [
            "email",
            "phone",
            "job_title",
            "account_name",
            "website",
            "industry",
            "address",
            "city",
            "country",
            "status",
            "source",
            "tags",
            "owner_human_id",
            "owner_agent_id",
            "annual_value",
            "notes",
            "external_source",
            "external_id",
            "meta_json",
            "company_id",
            "last_contacted_at",
        ],
        "field_types": {
            "owner_human_id": "int",
            "owner_agent_id": "int",
            "annual_value": "float",
            "company_id": "int",
            "last_contacted_at": "datetime",
            "meta_json": "json",
        },
        "aliases": {
            "create": ["create_customer", "add_customer"],
            "update": ["update_customer", "change_customer"],
            "delete": ["delete_customer"],
        },
    },

    # ── Deal ──────────────────────────────────────────────────────────────
    "deal": {
        "model": "Deal",
        "table": "deals",
        "label": "Deal",
        "category": "crm",
        "owner_col": "owner_user_id",
        "owner_via": None,
        "id_arg": "deal_id",
        "create_required": ["title", "customer_id"],
        # pipeline_id / stage_id optional when ensure-default-pipeline runs;
        # customer_id listed for create casting defaults (still required).
        "create_optional": {
            "pipeline_id": None,
            "stage_id": None,
            "customer_id": None,
        },
        "writable": [
            "title",
            "value",
            "currency",
            "status",
            "priority",
            "expected_close",
            "owner_human_id",
            "owner_agent_id",
            "position",
            "description",
            "lost_reason",
            "stage_id",
            "pipeline_id",
            "customer_id",
            "company_id",
        ],
        "clearable": [
            "value",
            "currency",
            "status",
            "priority",
            "expected_close",
            "owner_human_id",
            "owner_agent_id",
            "position",
            "description",
            "lost_reason",
            "stage_id",
            "pipeline_id",
            "company_id",
        ],
        "field_types": {
            "value": "float",
            "expected_close": "datetime",
            "owner_human_id": "int",
            "owner_agent_id": "int",
            "position": "int",
            "stage_id": "int",
            "pipeline_id": "int",
            "customer_id": "int",
            "company_id": "int",
        },
        "aliases": {
            "create": ["create_deal", "add_deal"],
            "update": ["update_deal", "change_deal", "move_deal", "win_deal", "lose_deal"],
            "delete": ["delete_deal"],
        },
    },

    # ── Pipeline ──────────────────────────────────────────────────────────
    "pipeline": {
        "model": "Pipeline",
        "table": "pipelines",
        "label": "Pipeline",
        "category": "crm",
        "owner_col": "owner_user_id",
        "owner_via": None,
        "id_arg": "pipeline_id",
        "create_required": ["name"],
        "writable": [
            "name",
            "description",
            "kind",
            "is_default",
            "company_id",
        ],
        "clearable": [
            "description",
            "kind",
            "is_default",
            "company_id",
        ],
        "field_types": {
            "is_default": "bool",
            "company_id": "int",
        },
        "aliases": {
            "create": ["ensure_sales_pipeline", "create_pipeline", "add_pipeline"],
            "update": ["update_pipeline", "change_pipeline"],
            "delete": ["delete_pipeline"],
        },
    },

    # ── Pipeline stage (ownership via parent pipeline) ────────────────────
    "pipeline_stage": {
        "model": "PipelineStage",
        "table": "pipeline_stages",
        "label": "Pipeline Stage",
        "category": "crm",
        "owner_col": None,
        "owner_via": {
            "parent": "pipeline",
            "fk": "pipeline_id",
            "parent_owner": "owner_user_id",
        },
        "id_arg": "stage_id",
        "create_required": ["name", "pipeline_id"],
        "writable": [
            "name",
            "stage_type",
            "color",
            "position",
            "probability",
            "pipeline_id",
        ],
        "clearable": [
            "stage_type",
            "color",
            "position",
            "probability",
        ],
        "field_types": {
            "position": "int",
            "probability": "int",
            "pipeline_id": "int",
        },
        "aliases": {
            "create": ["create_pipeline_stage", "add_pipeline_stage", "add_stage"],
            "update": ["update_pipeline_stage", "change_pipeline_stage", "update_stage"],
            "delete": ["delete_pipeline_stage", "delete_stage"],
        },
    },

    # ── Diary entry ───────────────────────────────────────────────────────
    "diary": {
        "model": "DiaryEntry",
        "table": "diary_entries",
        "label": "Diary Entry",
        "category": "crm",
        "owner_col": "owner_user_id",
        "owner_via": None,
        "id_arg": "diary_id",
        "create_required": ["title", "customer_id"],
        "writable": [
            "customer_id",
            "deal_id",
            "title",
            "start_at",
            "end_at",
            "location",
            "notes",
            "status",
            "owner_human_id",
            "owner_agent_id",
        ],
        "clearable": [
            "deal_id",
            "start_at",
            "end_at",
            "location",
            "notes",
            "status",
            "owner_human_id",
            "owner_agent_id",
        ],
        "field_types": {
            "customer_id": "int",
            "deal_id": "int",
            "start_at": "datetime",
            "end_at": "datetime",
            "owner_human_id": "int",
            "owner_agent_id": "int",
        },
        "aliases": {
            "create": ["schedule_meeting", "create_diary", "add_diary"],
            "update": ["update_diary", "change_diary", "update_meeting"],
            "delete": ["delete_diary", "cancel_meeting"],
        },
    },

    # ── Product ───────────────────────────────────────────────────────────
    "product": {
        "model": "Product",
        "table": "products",
        "label": "Product",
        "category": "crm",
        "owner_col": "owner_user_id",
        "owner_via": None,
        "id_arg": "product_id",
        "create_required": ["name"],
        "writable": [
            "name",
            "sku",
            "description",
            "kind",
            "price",
            "currency",
            "status",
            "tags",
            "benefits",
            "audience",
            "offer",
            "image_url",
            "external_source",
            "external_id",
            "meta_json",
            "company_id",
        ],
        "clearable": [
            "sku",
            "description",
            "kind",
            "price",
            "currency",
            "status",
            "tags",
            "benefits",
            "audience",
            "offer",
            "image_url",
            "external_source",
            "external_id",
            "meta_json",
            "company_id",
        ],
        "field_types": {
            "price": "float",
            "company_id": "int",
            "meta_json": "json",
        },
        "aliases": {
            "create": ["create_product", "add_product"],
            "update": ["update_product", "change_product"],
            "delete": ["delete_product"],
        },
    },

    # ── Customer activity ─────────────────────────────────────────────────
    "customer_activity": {
        "model": "CustomerActivity",
        "table": "customer_activities",
        "label": "Customer Activity",
        "category": "crm",
        "owner_col": "owner_user_id",
        "owner_via": None,
        "id_arg": "activity_id",
        "create_required": ["customer_id", "title"],
        "writable": [
            "customer_id",
            "kind",
            "title",
            "body",
            "deal_id",
            "agent_id",
            "human_id",
        ],
        "clearable": [
            "kind",
            "body",
            "deal_id",
            "agent_id",
            "human_id",
        ],
        "field_types": {
            "customer_id": "int",
            "deal_id": "int",
            "agent_id": "int",
            "human_id": "int",
        },
        "aliases": {
            "create": ["log_customer_activity", "create_customer_activity", "add_activity"],
            "update": ["update_customer_activity", "change_customer_activity"],
            "delete": ["delete_customer_activity"],
        },
    },
}


def get_specs() -> dict[str, dict[str, Any]]:
    """Return the CRM entity field specs registry."""
    return ENTITY_SPECS
