"""Catalog of connectable third-party apps (OAuth + API key)."""

# Each app:
#   id, name, category, description, auth_modes, fields (for API connect),
#   oauth (optional env client ids), scopes, icon (antd-friendly key)

INTEGRATION_APPS = {
    "shopify": {
        "id": "shopify",
        "name": "Shopify",
        "category": "commerce",
        "description": "Products, orders, customers, and storefront data for sales & ops agents.",
        "auth_modes": ["api_key", "oauth"],
        "color": "#96bf48",
        "docs_url": "https://shopify.dev/docs/api/admin-rest",
        "fields": [
            {"name": "shop_domain", "label": "Shop domain", "placeholder": "your-store.myshopify.com", "secret": False, "required": True},
            {"name": "access_token", "label": "Admin API access token", "placeholder": "shpat_…", "secret": True, "required": True},
            {"name": "api_version", "label": "API version (optional)", "placeholder": "2024-10", "secret": False, "required": False},
        ],
        "oauth": {
            "authorize_url": "https://{shop}/admin/oauth/authorize",
            "token_url": "https://{shop}/admin/oauth/access_token",
            "client_id_env": "SHOPIFY_CLIENT_ID",
            "client_secret_env": "SHOPIFY_CLIENT_SECRET",
            "scopes": "read_products,read_orders,read_customers,write_orders",
            "needs_shop": True,
        },
        "agent_capabilities": ["List products", "Summarise orders", "Draft customer replies from order context"],
    },
    "google": {
        "id": "google",
        "name": "Google (Workspace / Gemini)",
        "category": "productivity",
        "description": "Google account for Calendar, Drive context, and Gemini API access.",
        "auth_modes": ["api_key", "oauth"],
        "color": "#4285F4",
        "docs_url": "https://console.cloud.google.com/",
        "fields": [
            {"name": "api_key", "label": "Google API key (Gemini / Maps etc.)", "placeholder": "AIza…", "secret": True, "required": False},
            {"name": "client_email", "label": "Service account email (optional)", "placeholder": "bot@project.iam.gserviceaccount.com", "secret": False, "required": False},
            {"name": "private_key", "label": "Service account private key (optional)", "placeholder": "-----BEGIN PRIVATE KEY-----", "secret": True, "required": False},
        ],
        "oauth": {
            "authorize_url": "https://accounts.google.com/o/oauth2/v2/auth",
            "token_url": "https://oauth2.googleapis.com/token",
            "client_id_env": "GOOGLE_OAUTH_CLIENT_ID",
            "client_secret_env": "GOOGLE_OAUTH_CLIENT_SECRET",
            "scopes": "openid email profile https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/drive.readonly",
            "needs_shop": False,
        },
        "agent_capabilities": ["Read calendar context", "Use Gemini key", "Summarise Drive docs (when OAuth connected)"],
    },
    "google_business": {
        "id": "google_business",
        "name": "Google Business Profile",
        "category": "reviews",
        "description": "Reviews and local listing replies for reputation agents.",
        "auth_modes": ["oauth", "api_key"],
        "color": "#34A853",
        "docs_url": "https://developers.google.com/my-business",
        "fields": [
            {"name": "account_id", "label": "Account / location ID", "placeholder": "accounts/123/locations/456", "secret": False, "required": False},
            {"name": "access_token", "label": "OAuth access token (if you have one)", "placeholder": "ya29.…", "secret": True, "required": False},
            {"name": "refresh_token", "label": "Refresh token", "placeholder": "1//…", "secret": True, "required": False},
        ],
        "oauth": {
            "authorize_url": "https://accounts.google.com/o/oauth2/v2/auth",
            "token_url": "https://oauth2.googleapis.com/token",
            "client_id_env": "GOOGLE_OAUTH_CLIENT_ID",
            "client_secret_env": "GOOGLE_OAUTH_CLIENT_SECRET",
            "scopes": "https://www.googleapis.com/auth/business.manage",
            "needs_shop": False,
        },
        "agent_capabilities": ["List reviews", "Draft review replies", "Flag low ratings"],
    },
    "gmail": {
        "id": "gmail",
        "name": "Gmail",
        "category": "communication",
        "description": "Send and draft emails via Gmail for support & sales agents.",
        "auth_modes": ["oauth"],
        "color": "#EA4335",
        "docs_url": "https://developers.google.com/gmail/api",
        "fields": [
            {"name": "access_token", "label": "Access token", "placeholder": "ya29.…", "secret": True, "required": False},
            {"name": "refresh_token", "label": "Refresh token", "placeholder": "1//…", "secret": True, "required": False},
            {"name": "from_email", "label": "From address", "placeholder": "you@company.com", "secret": False, "required": False},
        ],
        "oauth": {
            "authorize_url": "https://accounts.google.com/o/oauth2/v2/auth",
            "token_url": "https://oauth2.googleapis.com/token",
            "client_id_env": "GOOGLE_OAUTH_CLIENT_ID",
            "client_secret_env": "GOOGLE_OAUTH_CLIENT_SECRET",
            "scopes": "https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly",
            "needs_shop": False,
        },
        "agent_capabilities": ["Draft emails", "Send via connected Gmail", "Summarise inbox threads"],
    },
    "google_sheets": {
        "id": "google_sheets",
        "name": "Google Sheets",
        "category": "productivity",
        "description": "Read/write spreadsheets for ops and reporting agents.",
        "auth_modes": ["oauth", "api_key"],
        "color": "#0F9D58",
        "docs_url": "https://developers.google.com/sheets/api",
        "fields": [
            {"name": "spreadsheet_id", "label": "Default spreadsheet ID", "placeholder": "1BxiM…", "secret": False, "required": False},
            {"name": "api_key", "label": "API key (public sheets)", "placeholder": "AIza…", "secret": True, "required": False},
            {"name": "access_token", "label": "OAuth access token", "placeholder": "ya29.…", "secret": True, "required": False},
        ],
        "oauth": {
            "authorize_url": "https://accounts.google.com/o/oauth2/v2/auth",
            "token_url": "https://oauth2.googleapis.com/token",
            "client_id_env": "GOOGLE_OAUTH_CLIENT_ID",
            "client_secret_env": "GOOGLE_OAUTH_CLIENT_SECRET",
            "scopes": "https://www.googleapis.com/auth/spreadsheets",
            "needs_shop": False,
        },
        "agent_capabilities": ["Read rows", "Append rows", "Build reports from sheet data"],
    },
    "slack": {
        "id": "slack",
        "name": "Slack",
        "category": "communication",
        "description": "Post updates and alerts into Slack channels.",
        "auth_modes": ["api_key", "oauth"],
        "color": "#4A154B",
        "docs_url": "https://api.slack.com/apps",
        "fields": [
            {"name": "bot_token", "label": "Bot user OAuth token", "placeholder": "xoxb-…", "secret": True, "required": True},
            {"name": "default_channel", "label": "Default channel", "placeholder": "#ops", "secret": False, "required": False},
        ],
        "oauth": {
            "authorize_url": "https://slack.com/oauth/v2/authorize",
            "token_url": "https://slack.com/api/oauth.v2.access",
            "client_id_env": "SLACK_CLIENT_ID",
            "client_secret_env": "SLACK_CLIENT_SECRET",
            "scopes": "chat:write,channels:read",
            "needs_shop": False,
        },
        "agent_capabilities": ["Post channel messages", "Notify on task completion"],
    },
    "hubspot": {
        "id": "hubspot",
        "name": "HubSpot",
        "category": "crm",
        "description": "CRM contacts, deals, and pipeline context for sales agents.",
        "auth_modes": ["api_key", "oauth"],
        "color": "#FF7A59",
        "docs_url": "https://developers.hubspot.com/",
        "fields": [
            {"name": "access_token", "label": "Private app access token", "placeholder": "pat-…", "secret": True, "required": True},
            {"name": "portal_id", "label": "Portal ID (optional)", "placeholder": "12345678", "secret": False, "required": False},
        ],
        "oauth": {
            "authorize_url": "https://app.hubspot.com/oauth/authorize",
            "token_url": "https://api.hubapi.com/oauth/v1/token",
            "client_id_env": "HUBSPOT_CLIENT_ID",
            "client_secret_env": "HUBSPOT_CLIENT_SECRET",
            "scopes": "crm.objects.contacts.read crm.objects.deals.read",
            "needs_shop": False,
        },
        "agent_capabilities": ["Lookup contacts", "Summarise deals", "Draft follow-ups"],
    },
    "stripe_connect": {
        "id": "stripe_connect",
        "name": "Stripe (your account)",
        "category": "payments",
        "description": "Your Stripe account for payment/ops agents (separate from platform billing).",
        "auth_modes": ["api_key"],
        "color": "#635BFF",
        "docs_url": "https://dashboard.stripe.com/apikeys",
        "fields": [
            {"name": "secret_key", "label": "Secret key", "placeholder": "sk_live_… or sk_test_…", "secret": True, "required": True},
            {"name": "publishable_key", "label": "Publishable key (optional)", "placeholder": "pk_…", "secret": False, "required": False},
        ],
        "oauth": None,
        "agent_capabilities": ["List recent charges", "Summarise revenue", "Flag failed payments"],
    },
    "woocommerce": {
        "id": "woocommerce",
        "name": "WooCommerce",
        "category": "commerce",
        "description": "WordPress store orders and products.",
        "auth_modes": ["api_key"],
        "color": "#96588A",
        "docs_url": "https://woocommerce.github.io/woocommerce-rest-api-docs/",
        "fields": [
            {"name": "store_url", "label": "Store URL", "placeholder": "https://shop.example.com", "secret": False, "required": True},
            {"name": "consumer_key", "label": "Consumer key", "placeholder": "ck_…", "secret": True, "required": True},
            {"name": "consumer_secret", "label": "Consumer secret", "placeholder": "cs_…", "secret": True, "required": True},
        ],
        "oauth": None,
        "agent_capabilities": ["List orders", "Product summaries", "Customer order lookups"],
    },
    "mailchimp": {
        "id": "mailchimp",
        "name": "Mailchimp",
        "category": "marketing",
        "description": "Email campaigns and audience lists for marketing agents.",
        "auth_modes": ["api_key"],
        "color": "#FFE01B",
        "docs_url": "https://mailchimp.com/developer/",
        "fields": [
            {"name": "api_key", "label": "API key", "placeholder": "xxxx-us21", "secret": True, "required": True},
            {"name": "server_prefix", "label": "Server prefix", "placeholder": "us21", "secret": False, "required": False},
        ],
        "oauth": None,
        "agent_capabilities": ["List audiences", "Draft campaign copy", "Summarise list growth"],
    },
    "zapier": {
        "id": "zapier",
        "name": "Zapier / Webhooks",
        "category": "automation",
        "description": "Outbound webhooks so agents can trigger Zaps and custom automations.",
        "auth_modes": ["api_key"],
        "color": "#FF4A00",
        "docs_url": "https://zapier.com/apps/webhook/integrations",
        "fields": [
            {"name": "webhook_url", "label": "Catch Hook URL", "placeholder": "https://hooks.zapier.com/hooks/catch/…", "secret": True, "required": True},
        ],
        "oauth": None,
        "agent_capabilities": ["Fire webhook with JSON payload", "Trigger multi-step automations"],
    },
    "notion": {
        "id": "notion",
        "name": "Notion",
        "category": "productivity",
        "description": "Pages and databases for knowledge & ops agents.",
        "auth_modes": ["api_key", "oauth"],
        "color": "#000000",
        "docs_url": "https://developers.notion.com/",
        "fields": [
            {"name": "integration_token", "label": "Internal integration token", "placeholder": "secret_… or ntn_…", "secret": True, "required": True},
            {"name": "default_database_id", "label": "Default database ID", "placeholder": "uuid", "secret": False, "required": False},
        ],
        "oauth": {
            "authorize_url": "https://api.notion.com/v1/oauth/authorize",
            "token_url": "https://api.notion.com/v1/oauth/token",
            "client_id_env": "NOTION_CLIENT_ID",
            "client_secret_env": "NOTION_CLIENT_SECRET",
            "scopes": "",
            "needs_shop": False,
        },
        "agent_capabilities": ["Search pages", "Create task pages", "Summarise databases"],
    },
    "dropbox": {
        "id": "dropbox",
        "name": "Dropbox",
        "category": "storage",
        "description": "Store and train agents on files from your Dropbox (Training library).",
        "auth_modes": ["api_key", "oauth"],
        "color": "#0061FF",
        "docs_url": "https://www.dropbox.com/developers",
        "fields": [
            {"name": "access_token", "label": "Access token", "placeholder": "sl.B…", "secret": True, "required": True},
            {"name": "root_path", "label": "Training root path", "placeholder": "/AI-Training", "secret": False, "required": False},
        ],
        "oauth": {
            "authorize_url": "https://www.dropbox.com/oauth2/authorize",
            "token_url": "https://api.dropboxapi.com/oauth2/token",
            "client_id_env": "DROPBOX_APP_KEY",
            "client_secret_env": "DROPBOX_APP_SECRET",
            "scopes": "",
            "needs_shop": False,
        },
        "agent_capabilities": ["Read training files", "Import docs into library", "Store agent deliverables"],
    },
    "google_cloud_storage": {
        "id": "google_cloud_storage",
        "name": "Google Cloud Storage",
        "category": "storage",
        "description": "Bucket storage for training files and agent knowledge (GCS).",
        "auth_modes": ["api_key"],
        "color": "#4285F4",
        "docs_url": "https://cloud.google.com/storage/docs",
        "fields": [
            {"name": "bucket", "label": "Bucket name", "placeholder": "my-training-bucket", "secret": False, "required": True},
            {"name": "prefix", "label": "Object prefix (folder)", "placeholder": "ai-training", "secret": False, "required": False},
            {"name": "access_token", "label": "OAuth access token (optional)", "placeholder": "ya29.…", "secret": True, "required": False},
            {"name": "client_email", "label": "Service account email", "placeholder": "sa@project.iam.gserviceaccount.com", "secret": False, "required": False},
            {"name": "private_key", "label": "Service account private key", "placeholder": "-----BEGIN PRIVATE KEY-----", "secret": True, "required": False},
            {"name": "service_account_json", "label": "Full service account JSON (optional)", "placeholder": "{ \"type\": \"service_account\", … }", "secret": True, "required": False},
        ],
        "oauth": None,
        "agent_capabilities": ["Read training objects", "Upload knowledge files", "Browse bucket prefixes"],
    },
}


def list_apps() -> list[dict]:
    return [public_app(a) for a in INTEGRATION_APPS.values()]


def get_app(app_id: str) -> dict | None:
    return INTEGRATION_APPS.get((app_id or "").strip().lower())


def public_app(app: dict, *, oauth_ready: bool | None = None) -> dict:
    """Safe catalog entry for the frontend (no secrets)."""
    oauth = app.get("oauth")
    return {
        "id": app["id"],
        "name": app["name"],
        "category": app["category"],
        "description": app["description"],
        "auth_modes": list(app.get("auth_modes") or []),
        "color": app.get("color"),
        "docs_url": app.get("docs_url"),
        "fields": [
            {
                "name": f["name"],
                "label": f["label"],
                "placeholder": f.get("placeholder", ""),
                "secret": bool(f.get("secret")),
                "required": bool(f.get("required")),
            }
            for f in (app.get("fields") or [])
        ],
        "supports_oauth": bool(oauth),
        "oauth_ready": oauth_ready,
        "oauth_scopes": (oauth or {}).get("scopes") if oauth else None,
        "oauth_needs_shop": bool((oauth or {}).get("needs_shop")),
        "agent_capabilities": list(app.get("agent_capabilities") or []),
    }
