"""Agent template catalog. Add new entries here — seed upserts by name on startup."""

# (name, type, description, unique_fields, est_cost)
SEED_TEMPLATES = [
    # ── Main orchestrator (always pin to top of hierarchy) ─────────
    ("Main AI Orchestrator", "orchestrator",
     "Top-level commander for your whole workspace: routes work to leads and project agents, "
     "keeps company priorities aligned, and is always listed first so you can find it instantly.",
     [{"name": "mission", "label": "Workspace mission", "placeholder": "e.g. Grow all client brands profitably"},
      {"name": "priorities", "label": "Top priorities", "placeholder": "Sales, support quality, compliance"},
      {"name": "escalation", "label": "Escalate to human when…", "placeholder": "Refunds > £500, legal risk, VIP complaints"}],
     "~$2.00 / day"),

    # ── Leadership / hierarchy ────────────────────────────────────
    ("Lead Agent / Team Lead", "lead",
     "Orchestrates a team of agents: prioritises work, delegates tasks, reviews deliverables, and reports status to you.",
     [{"name": "team_goal", "label": "Team mission / goal", "placeholder": "e.g. Book 10 demos a week for EICR services"},
      {"name": "reporting_style", "label": "How should the lead report?", "placeholder": "Daily summary / only blockers / weekly roll-up"},
      {"name": "delegation_rules", "label": "Delegation rules", "placeholder": "Sales → outreach agents, coding → coder agents"}],
     "~$1.50 / day"),
    ("Operations Lead", "lead",
     "Runs multi-agent workflows across sales, support and ops — assigns owners and tracks completion.",
     [{"name": "scope", "label": "Ops scope", "placeholder": "Inbox, bookings, follow-ups"},
      {"name": "sla", "label": "SLAs", "placeholder": "Reply within 2 hours, book within 24h"}],
     "~$1.40 / day"),
    ("Sales Lead Agent", "lead",
     "Owns the sales pod: pipeline hygiene, coaching scripts, and assigning leads to outreach agents.",
     [{"name": "pipeline_stages", "label": "Pipeline stages", "placeholder": "New → Qualified → Proposal → Won"},
      {"name": "quota", "label": "Team quota", "placeholder": "20 qualified meetings / month"}],
     "~$1.30 / day"),

    # ── Business / sales ──────────────────────────────────────────
    ("Sales Outreach Agent", "sales",
     "Finds leads, drafts personalised outreach and follows up automatically.",
     [{"name": "product", "label": "What are you selling?", "placeholder": "e.g. EICR inspections in Greater Manchester"},
      {"name": "target", "label": "Target customer", "placeholder": "e.g. landlords with 3+ properties"}],
     "~$0.80 / day"),
    ("Lead Qualifier", "sales",
     "Scores inbound enquiries, asks qualifying questions, and routes hot leads to you.",
     [{"name": "icp", "label": "Ideal customer profile", "placeholder": "Budget, industry, company size"},
      {"name": "disqualify", "label": "Disqualify if…", "placeholder": "e.g. no budget, outside service area"}],
     "~$0.45 / day"),
    ("Cold Call Scriptwriter", "sales",
     "Writes call openers, objection handlers and voicemail scripts for your offer.",
     [{"name": "offer", "label": "Offer / product", "placeholder": "e.g. free EICR survey for multi-lets"},
      {"name": "persona", "label": "Caller persona", "placeholder": "e.g. calm, local, no hard sell"}],
     "~$0.35 / day"),
    ("LinkedIn Outreach", "sales",
     "Drafts connection notes, follow-ups and soft CTAs for LinkedIn prospecting.",
     [{"name": "role", "label": "Your role / company", "placeholder": "e.g. Founder at TAS Electrical"},
      {"name": "goal", "label": "Goal", "placeholder": "e.g. book discovery calls with facilities managers"}],
     "~$0.40 / day"),

    # ── Support / CX ───────────────────────────────────────────────
    ("Customer Support Agent", "support",
     "Answers customer questions by email/SMS using your business info.",
     [{"name": "business_name", "label": "Business name", "placeholder": "e.g. TAS Electrical"},
      {"name": "faq", "label": "Key info / FAQ", "placeholder": "Opening hours, services, pricing basics"}],
     "~$0.50 / day"),
    ("Review Responder", "reviews",
     "Monitors and replies to Google reviews in your brand voice.",
     [{"name": "business_name", "label": "Business name", "placeholder": ""},
      {"name": "voice", "label": "Reply style", "placeholder": "e.g. warm, professional, always thanks the customer"}],
     "~$0.30 / day"),
    ("Complaint Handler", "support",
     "De-escalates angry customers, proposes remedies, and drafts apology + resolution emails.",
     [{"name": "policy", "label": "Refund / remedy policy", "placeholder": "e.g. rework within 14 days"},
      {"name": "escalation", "label": "Escalate to", "placeholder": "e.g. ops@company.com"}],
     "~$0.40 / day"),
    ("Appointment Booker", "booking",
     "Handles booking requests, confirms slots and sends reminders.",
     [{"name": "services", "label": "Bookable services", "placeholder": "e.g. EICR, fire alarm service"},
      {"name": "hours", "label": "Working hours", "placeholder": "e.g. Mon–Fri 8am–5pm"}],
     "~$0.40 / day"),

    # ── Content / marketing ────────────────────────────────────────
    ("Content Writer Agent", "content",
     "Writes blog posts, service pages and social content on a schedule.",
     [{"name": "topics", "label": "Topics / niche", "placeholder": "e.g. fire safety compliance"},
      {"name": "tone", "label": "Brand tone", "placeholder": "e.g. plain-English, authoritative"}],
     "~$0.60 / day"),
    ("SEO Content Strategist", "marketing",
     "Keyword clusters, briefs, meta titles/descriptions and internal-link plans.",
     [{"name": "niche", "label": "Niche / city", "placeholder": "e.g. electrician Manchester"},
      {"name": "competitors", "label": "Competitors (optional)", "placeholder": "URLs or brand names"}],
     "~$0.55 / day"),
    ("Social Media Manager", "marketing",
     "Weekly content calendar, captions and hashtags for LinkedIn, Instagram, X.",
     [{"name": "platforms", "label": "Platforms", "placeholder": "LinkedIn + Instagram"},
      {"name": "brand_voice", "label": "Brand voice", "placeholder": "Practical, trustworthy, UK English"}],
     "~$0.50 / day"),
    ("Email Newsletter Writer", "marketing",
     "Subject lines, body copy and CTAs for weekly/monthly newsletters.",
     [{"name": "audience", "label": "Audience", "placeholder": "Existing customers / landlords"},
      {"name": "frequency", "label": "Cadence", "placeholder": "Weekly"}],
     "~$0.35 / day"),

    # ── Engineering / coders ───────────────────────────────────────
    ("Full-Stack Developer", "coding",
     "Builds features end-to-end: APIs, UI, DB, tests. Prefer clear diffs and runnable code.",
     [{"name": "stack", "label": "Preferred stack", "placeholder": "e.g. FastAPI + React + Postgres"},
      {"name": "repo_context", "label": "Project context", "placeholder": "App name, monorepo layout, constraints"}],
     "~$1.20 / day"),
    ("Backend API Engineer", "coding",
     "Designs REST/GraphQL endpoints, auth, validation, and SQLAlchemy/Prisma models.",
     [{"name": "framework", "label": "Framework", "placeholder": "FastAPI / Nest / Django"},
      {"name": "db", "label": "Database", "placeholder": "Postgres / SQLite"}],
     "~$1.00 / day"),
    ("Frontend Engineer", "coding",
     "React/Vue components, state, forms, accessibility and polished UX.",
     [{"name": "framework", "label": "UI stack", "placeholder": "React + Ant Design / Tailwind"},
      {"name": "design_notes", "label": "Design notes", "placeholder": "Brand colours, mobile-first"}],
     "~$1.00 / day"),
    ("Python Automation Coder", "coding",
     "Scripts for scraping, ETL, reports, bots, and internal tools.",
     [{"name": "language", "label": "Language / runtime", "placeholder": "Python 3.11 + httpx"},
      {"name": "integrations", "label": "Systems to talk to", "placeholder": "Sheets, CRM, email"}],
     "~$0.90 / day"),
    ("Code Reviewer", "coding",
     "Reviews PRs for bugs, security, performance and style; suggests concrete patches.",
     [{"name": "languages", "label": "Languages", "placeholder": "Python, TypeScript, SQL"},
      {"name": "standards", "label": "Standards", "placeholder": "PEP8, OWASP basics, no secrets"}],
     "~$0.70 / day"),
    ("Bug Fixer", "coding",
     "Reproduces issues from logs/stack traces and produces minimal, tested fixes.",
     [{"name": "runtime", "label": "Runtime", "placeholder": "Node 20 / Python 3.11"},
      {"name": "error_log", "label": "Typical error source", "placeholder": "Sentry, server logs, user reports"}],
     "~$0.85 / day"),
    ("DevOps / Infra Agent", "coding",
     "Docker, nginx, CI/CD, env config, health checks and deploy runbooks.",
     [{"name": "host", "label": "Hosting", "placeholder": "VPS + Docker / Kubernetes"},
      {"name": "stack", "label": "Services", "placeholder": "API, worker, Postgres, Ollama"}],
     "~$0.90 / day"),
    ("SQL & Data Engineer", "coding",
     "Schemas, migrations, queries, dashboards and data-quality checks.",
     [{"name": "warehouse", "label": "DB / warehouse", "placeholder": "Postgres / BigQuery"},
      {"name": "domain", "label": "Domain", "placeholder": "billing, usage, agents"}],
     "~$0.75 / day"),
    ("QA / Test Engineer", "coding",
     "Writes test plans, unit/integration cases, and regression checklists.",
     [{"name": "framework", "label": "Test stack", "placeholder": "pytest / Playwright / Jest"},
      {"name": "app_under_test", "label": "App under test", "placeholder": "AI Business Assistant"}],
     "~$0.65 / day"),
    ("Security Reviewer", "coding",
     "Threat models APIs, auth, secrets handling and OWASP top risks; actionable fixes.",
     [{"name": "scope", "label": "Scope", "placeholder": "Auth, billing webhook, multi-tenant data"},
      {"name": "stack", "label": "Stack", "placeholder": "FastAPI + JWT + Stripe"}],
     "~$0.80 / day"),
    ("Tech Docs Writer", "coding",
     "API docs, README, runbooks and architecture notes developers actually use.",
     [{"name": "audience", "label": "Audience", "placeholder": "Internal engineers / customers"},
      {"name": "format", "label": "Format", "placeholder": "Markdown / OpenAPI comments"}],
     "~$0.50 / day"),
    ("Mobile App Helper", "coding",
     "React Native / Flutter screens, navigation and API wiring guidance.",
     [{"name": "platform", "label": "Platform", "placeholder": "React Native / Flutter / iOS"},
      {"name": "backend_api", "label": "Backend base URL", "placeholder": "https://api.example.com"}],
     "~$0.90 / day"),

    # ── Ops / business ─────────────────────────────────────────────
    ("Research Analyst", "ops",
     "Market scans, competitor briefs and source-backed summaries.",
     [{"name": "industry", "label": "Industry", "placeholder": "UK electrical compliance"},
      {"name": "depth", "label": "Depth", "placeholder": "Quick scan / deep dive"}],
     "~$0.55 / day"),
    ("Meeting Summariser", "ops",
     "Turns notes or transcripts into actions, owners and follow-up emails.",
     [{"name": "format", "label": "Output format", "placeholder": "Bullets + action table"},
      {"name": "timezone", "label": "Timezone", "placeholder": "Europe/London"}],
     "~$0.35 / day"),
    ("Invoice & Accounts Helper", "ops",
     "Drafts invoices, payment chasers and simple cashflow notes (not formal accounting advice).",
     [{"name": "currency", "label": "Currency", "placeholder": "GBP"},
      {"name": "payment_terms", "label": "Payment terms", "placeholder": "14 days net"}],
     "~$0.30 / day"),
    ("HR Screening Assistant", "ops",
     "Screens CVs against a job description and drafts interview questions.",
     [{"name": "role_title", "label": "Role title", "placeholder": "Junior electrician / React developer"},
      {"name": "must_haves", "label": "Must-haves", "placeholder": "3+ years, CSCS, TypeScript"}],
     "~$0.40 / day"),
    ("Legal Draft Helper", "ops",
     "First-pass contracts, policies and notices — always for lawyer review, not legal advice.",
     [{"name": "jurisdiction", "label": "Jurisdiction", "placeholder": "England & Wales"},
      {"name": "doc_type", "label": "Document type", "placeholder": "NDA / service terms / privacy notice"}],
     "~$0.50 / day"),
    ("Product Manager", "ops",
     "User stories, acceptance criteria, prioritisation and release notes.",
     [{"name": "product", "label": "Product", "placeholder": "AI Business Assistant"},
      {"name": "users", "label": "Primary users", "placeholder": "SMB owners, trades, agencies"}],
     "~$0.55 / day"),
    ("Translator / Localiser", "ops",
     "Translates UI strings and marketing copy while preserving tone and technical terms.",
     [{"name": "from_lang", "label": "From", "placeholder": "English"},
      {"name": "to_lang", "label": "To", "placeholder": "Polish / Arabic / Spanish"}],
     "~$0.35 / day"),
]

NOTIFY_FIELDS = [
    {"name": "notify_email", "label": "Deliver results to email (optional)", "placeholder": "you@business.com"},
    {"name": "notify_sms", "label": "Deliver results by SMS (optional)", "placeholder": "+447..."},
]
